$activeBorderColor = rgba(00e5ffff) rgba(1f8fffff) 45deg
$inactiveBorderColor = rgba(0b2a3aaa)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
